services:
  - type: web
    name: ems
    env: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn ems.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
