# Generated by Django 6.0.1 on 2026-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_registerdetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('about_event', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('vacancy', models.PositiveIntegerField()),
                ('ratings', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('img_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
