# Generated by Django 6.0.1 on 2026-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_img', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
